### ISSUE TITLE
Wrong icon in iOS multitask view

### ISSUE THREAD

**Issue by surajpindoria** [phonegap/phonegap-app-developer#428]
In iOS, with the app running, press the home button twice to bring up the multitask view. Notice the icon for the app is actually the default Cordova icon.

![img_2874](https://cloud.githubusercontent.com/assets/6467569/15623037/2f87ae38-2424-11e6-885e-7886714163d6.PNG)

**Comment by mwbrooks** [comment]
Good find!

**Comment by surajpindoria** [comment]
Also in the Settings menu

![file_000](https://cloud.githubusercontent.com/assets/6467569/17338951/84b2e63a-589e-11e6-8f86-55c4fc2d29ee.png)

**Comment by surajpindoria** [comment]
So it looks like we are missing a few icon types in the dev app, which is why this issue is occurring. [This](https://makeappicon.com/ios9icon) shows which icons are needed for iOS 9.

Specifically:

- Icon-Small@3x
- Icon-40@3x
- Icon-83.5@2x

Icon-Small@3x is the one that fixes this particular issue.

@timkim

**Comment by mikeoliveira** [comment]
Some solution to this bug ??

**Comment by surajpindoria** [comment]
We just need to add those missing icon files and that solves the issue.

Are you seeing this within your own apps @mikeoliveira?

**Comment by mikeoliveira** [comment]
i work with build in cloud (phonegap build), i copy the images to **MyApp\www\res\icon\ios**  
yet still continues with the bug, Do i need change the **config.xml** ?

**Comment by surajpindoria** [comment]
You will need to update your `config.xml` to use those icons, take a look at that file for this project to see how it is done. But there is a bug with Build where some icons do not get copied over properly. Still working on it.

https://github.com/phonegap/phonegap-cli/issues/636

**Comment by wuppit** [comment]
Hello, I am waiting since cli-6.0.0 (around 6 months) to create apps with phonegap build with the correct icons. Like shown in this thread, the push, the multiview and the settings icon on iphone 6+/6s+ is the default pgb icon.

It would be great if this bug could be corrected by the build team. For us it is a **really important bug**, you cannot sell app creations with missing icons.

**@surajpindoria** you are the first phonegap member, who seems to realize, that it is a bug in pgb, thanks for that!!!! All my hope is with you ;-)

**Comment by surajpindoria** [comment]
Hey @wuppit,

I am chatting with the Build guys now and they are looking into it. I'll post an update when I know more.

**Comment by surajpindoria** [comment]
The issue with Build has been fixed!

@wuppit @mikeoliveira

**Comment by wuppit** [comment]
**That's so fantastic, THANK YOU!!!!!!!!**

**Comment by surajpindoria** [comment]
Tested this out, above commit does the trick.

**Comment by scrawner** [comment]
I changed config.xml and added the icons but the problem wasn't solved. Is there anything else that I need to do?

`<icon src="res/icon/ios/icon-57.png"            gap:platform="ios"        width="57" height="57" />
    <icon src="res/icon/ios/icon-72.png"            gap:platform="ios"        width="72" height="72" />
    <icon src="res/icon/ios/icon-small@3x.png"      gap:platform="ios"        width="87" height="87" />    
    <icon src="res/icon/ios/icon-57-2x.png"         gap:platform="ios"        width="114" height="114" />
    <icon src="res/icon/ios/icon-40@3x.png"         gap:platform="ios"        width="120" height="120" />    
    <icon src="res/icon/ios/icon-72-2x.png"         gap:platform="ios"        width="144" height="144" />
    <icon src="res/icon/ios/icon-83.5@2x.png"       gap:platform="ios"        width="167" height="167" />    `

**Comment by JakenHerman** [comment]
You're a life saver @surajpindoria :1st_place_medal:
